### ISSUE TITLE
Data unavailable

### ISSUE THREAD

**Issue by YongxiangLei** [jtstoffel/tube-mpc#2]
Hi,

I found the following error when I try to reproduce your results. It shows that it lacks the data .mat file.
I would be so grateful if you can help.
![1688553466404](https://github.com/jtstoffel/tube-mpc/assets/28838060/33100da0-7d94-4d6b-86a0-ab9f4d97999f)
Best regards,
Yong

**Comment by jtstoffel** [comment]
The first time you run `sysout = preprocess_system(system, useDataFile)` for a system you have defined, you will need to set the `useDataFile` flag to false. You can then set it to true in order to skip the preprocessing step for future runs as long as you are not changing the system data you are working with.
